corpus:
  input: 'data/random_patents_100000.pkl'
  use_col: 'contents'
  output: 'data/corpus_sudachi.txt'
  use_field: ['ab', 'cl', 'de']
  batch_size: 100000
  n_jobs: -1


w2v:
    input: 'data/corpus_sudachi_linesentence-fmt.txt'
    output: 'model/patent_w2v.model'
    size: 300
    window: 10
    min_count: 10
    sg: 1 # Skip-gram
    negative: 5
    iter: 5
    workers: 8
